export const HIVE_API_TOKEN = "HIVE_API_TOKEN";
export const HIVE_USER_NAME = "HIVE_USER_NAME";
export const IS_LOGIN = "HIVE_IS_LOGIN"
export const HIVE_USER_PASSWORD="HIVE_USER_PASSWORD"
export const HIVE_REMENBER_USERNAME = "HIVE_REMENBER_USERNAME"
